### PR TITLE
Make imports in generated files predictable

### PR DESCRIPTION
**Pull request by giuscri**
The import list is manipulated as a set. Let's sort it before printing

### CODE REVIEW

**Comment by giuscri** [comment]
cc @calippo

**Comment by calippo** [comment]
maybe we can configure scalafmt to take care of this?

**Comment by calippo** [comment]
Formatting is performed here https://github.com/buildo/retro/blob/master/tapiro/core/src/main/scala/io/buildo/tapiro/Formatter.scala

**Comment by giuscri** [comment]
> maybe we can configure scalafmt to take care of this?

If [this](https://github.com/scalameta/scalafmt/pull/1038#issuecomment-328357433) comment is still relevant, scalafmt doesn't and won't implement this.

Looking at the docs, the only thing that's about import sorting is for strings inside braces like `import foo.{abc, def}`

https://scalameta.org/scalafmt/docs/configuration.html#sortimports

**Comment by calippo** [comment]
Since we're auto-generating the code the problem doesn't apply in our case.

**Review by calippo — APPROVED** [review]
lgtm

**Comment by gabro** [comment]
> maybe we can configure scalafmt to take care of this?


Sorting imports is not a problem that can be solved syntactically. Because of relative imports, swapping two lines can change the program's semantics.

**Comment by giuscri** [comment]
ping

**Pull request merged**
